PR_append = ".1"

VERSION = "${DISTRO_VERSION}"
VERSION_ID = "${DISTRO_VERSION_ID}"
CODENAME = "${DISTRO_CODENAME}"
PRETTY_NAME = "${DISTRO_NAME} ${VERSION}${@' (%s)' % DISTRO_CODENAME if 'DISTRO_CODENAME' in d else ''}"
UPDATE_URL = "${DISTRO_UPDATE_URL}"

OS_RELEASE_FIELDS += "BUILD_ID CODENAME UPDATE_URL"
