#!/bin/sh

set -u

bootslot=$(fw_printenv -n bootslot 2>&-)
if [ $? -eq 0 ]; then
    echo "Updating image"
    swupdate -f /etc/swupdate.cfg -e stable,bootslot"${bootslot}" --download ''
else
    echo "Failed to extract bootslot value from U-Boot"
fi
